name: dbt CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}  
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake==1.8.4



      - name: Run dbt deps
        run: dbt deps

     

      - name: Run dbt run
        run: dbt run --profiles-dir .

      - name: Run dbt test
        run: dbt test --profiles-dir .

      - name: Run dbt docs generate
        run: dbt docs generate --profiles-dir .

      - name: Upload dbt docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target

